version: '3'

services:
  telegram_bot:
    build: telegram_bot
    ports:
      - "8443:8000"
      - "8444:5432"
    depends_on:
      - fastapi_app
      - postgres
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
    networks:
      - mynetwork

  fastapi_app:
    build: fastapi_app
    ports:
      - "8000:8000"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge