version: '3'

services:
  telegram_bot:
    build:
      context: ./telegram_bot
    depends_on:
      - fastapi_app
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
    restart: always
    networks:
      - recipe_network
    volumes:
      - ./telegram_bot:/app
    container_name: recipe_telegram_bot

  fastapi_app:
    build:
      context: ./fastapi_app
    expose:
      - 8000
    # If using GPU, uncomment the following lines
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]
    restart: always
    networks:
      - recipe_network
    volumes:
      - ./fastapi_app:/app
    container_name: recipe_fastapi_app

networks:
  recipe_network:
    driver: bridge